# action.yml
name: 'FleetCmdr'
description: 'Upload alloy condigs'
inputs:
  host:
    description: 'fleet management endpoint'
    required: true
  user:
    description: 'fleet management username'
    required: true
  token:
    description: 'fleet management token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    FLEET_MANAGEMENT_HOST: ${{ inputs.host }}
    FLEET_MANAGEMENT_USER: ${{ inputs.user }}
    FLEET_MANAGEMENT_TOKEN: ${{ inputs.token }}